export const MUSCLES = {
  Chest: "#4A91EB",
  Back: "#9B6DFF",
  Legs: "#34C87A",
  Shoulders: "#F5A623",
  Arms: "#FF6B9D",
  Core: "#4DD9E8",
  Cardio: "#FF7A59",
};

const yt = (q) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q + " proper form")}`;

export const WORKOUTS = [
  { id: "bench_press", name: "Smith Machine Bench Press", muscle: "Chest", targetMuscle: "Mid Chest", equipment: "Smith Machine", video: yt("smith machine bench press") },
  { id: "incline_db_press", name: "Incline Dumbbell Press", muscle: "Chest", targetMuscle: "Upper Chest", equipment: "Dumbbell", video: yt("incline dumbbell press") },
  { id: "pushups", name: "Push-ups", muscle: "Chest", targetMuscle: "Overall Chest", equipment: "Bodyweight", video: yt("pushups") },
  { id: "cable_fly", name: "Lower Chest Fly", muscle: "Chest", targetMuscle: "Lower Chest", equipment: "Cable / Machine", video: yt("lower chest fly") },
  { id: "upper_cable_fly", name: "Upper Chest Cable Fly", muscle: "Chest", targetMuscle: "Upper Chest", equipment: "Cable", video: yt("upper chest cable fly") },
  { id: "dips", name: "Chest Dips", muscle: "Chest", targetMuscle: "Lower Chest", equipment: "Dip bars", video: yt("chest dips") },
  { id: "pec_dec_fly", name: "Pec Dec Fly", muscle: "Chest", targetMuscle: "Inner Chest", equipment: "Machine", video: yt("pec dec fly") },

  { id: "pullups", name: "Pull-ups", muscle: "Back", targetMuscle: "Upper Lats", equipment: "Bodyweight", video: yt("pull ups") },
  { id: "barbell_row", name: "Bent Over Barbell Row", muscle: "Back", targetMuscle: "Overall Back", equipment: "Barbell", video: yt("bent over barbell row") },
  { id: "lat_pulldown", name: "Lat Pulldown", muscle: "Back", targetMuscle: "Upper Lats", equipment: "Cable", video: yt("lat pulldown") },
  { id: "seated_row", name: "Seated Cable Row", muscle: "Back", targetMuscle: "Mid Back", equipment: "Cable", video: yt("seated cable row") },
  { id: "deadlift", name: "Deadlift", muscle: "Back", targetMuscle: "Lower Back", equipment: "Barbell", video: yt("deadlift") },
  { id: "one_arm_db_row", name: "One Arm Dumbbell Row", muscle: "Back", targetMuscle: "Lower Lats", equipment: "Dumbbell", video: yt("one arm dumbbell row") },
  { id: "chest_supported_db_row", name: "Chest Supported Dumbbell Row", muscle: "Back", targetMuscle: "Mid Back", equipment: "Dumbbell", video: yt("chest supported dumbbell row") },
  { id: "single_arm_high_row", name: "Single Arm High Cable Row", muscle: "Back", targetMuscle: "Upper Lats", equipment: "Cable", video: yt("single arm high cable row") },
  { id: "dead_hang", name: "Dead Hang", muscle: "Back", targetMuscle: "Grip / Lats", equipment: "Bodyweight", video: yt("dead hang") },

  { id: "squat", name: "Barbell Squat", muscle: "Legs", targetMuscle: "Quads / Glutes", equipment: "Barbell", video: yt("barbell squat") },
  { id: "rdl", name: "Romanian Deadlift", muscle: "Legs", targetMuscle: "Hamstrings", equipment: "Dumbbell", video: yt("romanian deadlift dumbbell") },
  { id: "leg_press", name: "Leg Press", muscle: "Legs", targetMuscle: "Quads", equipment: "Machine", video: yt("leg press") },
  { id: "lunges", name: "Walking Lunges", muscle: "Legs", targetMuscle: "Quads / Glutes", equipment: "Dumbbell", video: yt("walking lunges") },
  { id: "calf_raise", name: "Standing Calf Raise", muscle: "Legs", targetMuscle: "Calves", equipment: "Machine", video: yt("standing calf raise") },
  { id: "sumo_squat", name: "Heavy Sumo Squat", muscle: "Legs", targetMuscle: "Abductor / Inner Thighs", equipment: "Dumbbell", video: yt("heavy sumo squat dumbbell") },
  { id: "hack_squat", name: "Hack Squat", muscle: "Legs", targetMuscle: "Overall Quad", equipment: "Machine", video: yt("hack squat") },
  { id: "lying_leg_curl", name: "Lying Hamstring Curl", muscle: "Legs", targetMuscle: "Hamstrings", equipment: "Machine", video: yt("lying hamstring curl") },
  { id: "leg_extension", name: "Leg Extension", muscle: "Legs", targetMuscle: "Inner Quad", equipment: "Machine", video: yt("leg extension") },
  { id: "hip_thrust", name: "Hip Thrust", muscle: "Legs", targetMuscle: "Glutes", equipment: "Barbell", video: yt("hip thrust") },

  { id: "ohp", name: "Overhead Press", muscle: "Shoulders", targetMuscle: "Front Delts", equipment: "Barbell", video: yt("overhead press") },
  { id: "lateral_raise", name: "Lateral Raise", muscle: "Shoulders", targetMuscle: "Side Delts", equipment: "Dumbbell", video: yt("lateral raise") },
  { id: "front_raise", name: "Front Raise", muscle: "Shoulders", targetMuscle: "Front Delts", equipment: "Dumbbell", video: yt("front raise") },
  { id: "face_pull", name: "Face Pull", muscle: "Shoulders", targetMuscle: "Rear Delts", equipment: "Cable", video: yt("face pull") },
  { id: "arnold_press", name: "Arnold Press", muscle: "Shoulders", targetMuscle: "Front / Side Delts", equipment: "Dumbbell", video: yt("arnold press") },
  { id: "db_shoulder_press", name: "Dumbbell Shoulder Press", muscle: "Shoulders", targetMuscle: "Front Delts", equipment: "Dumbbell", video: yt("dumbbell shoulder press") },
  { id: "rear_delt_fly", name: "Rear Delt Fly", muscle: "Shoulders", targetMuscle: "Rear Delts", equipment: "Machine", video: yt("rear delt fly") },
  { id: "shrugs", name: "Shrugs", muscle: "Shoulders", targetMuscle: "Traps", equipment: "Dumbbell", video: yt("shrugs") },

  { id: "incline_bicep_curl", name: "Incline Bicep Curl", muscle: "Arms", targetMuscle: "Biceps Long Head", equipment: "Dumbbell", video: yt("incline bicep curl") },
  { id: "alternate_db_curl", name: "Alternate Dumbbell Curl", muscle: "Arms", targetMuscle: "Biceps", equipment: "Dumbbell", video: yt("alternate dumbbell curl") },
  { id: "barbell_curl", name: "Barbell Curl", muscle: "Arms", targetMuscle: "Biceps", equipment: "Barbell", video: yt("barbell curl") },
  { id: "hammer_curl", name: "Hammer Curl", muscle: "Arms", targetMuscle: "Brachialis", equipment: "Dumbbell", video: yt("hammer curl") },
  { id: "preacher_curl", name: "Preacher Curl", muscle: "Arms", targetMuscle: "Biceps Short Head", equipment: "Machine", video: yt("preacher curl") },
  { id: "cable_bicep_curl", name: "Cable Bicep Curl", muscle: "Arms", targetMuscle: "Biceps", equipment: "Cable", video: yt("cable bicep curl") },
  { id: "biceps_superset", name: "Biceps Superset", muscle: "Arms", targetMuscle: "Biceps", equipment: "Varies", video: yt("biceps superset") },

  { id: "triceps_ohp", name: "Overhead Tricep Extension", muscle: "Arms", targetMuscle: "Triceps Long Head", equipment: "Dumbbell", video: yt("overhead tricep extension") },
  { id: "tricep_pushdown", name: "Tricep Pushdown", muscle: "Arms", targetMuscle: "Triceps Lateral Head", equipment: "Cable", video: yt("tricep pushdown") },
  { id: "cgbp", name: "Close-Grip Bench Press", muscle: "Arms", targetMuscle: "Triceps Overall", equipment: "Barbell", video: yt("close grip bench press") },
  { id: "skull_crusher", name: "Skull Crusher", muscle: "Arms", targetMuscle: "Triceps Long Head", equipment: "Barbell", video: yt("skull crusher") },
  { id: "tricep_kickback", name: "Tricep Kickback", muscle: "Arms", targetMuscle: "Triceps Lateral Head", equipment: "Cable", video: yt("cable tricep kickback") },
  { id: "wrist_curl", name: "Wrist Curl", muscle: "Arms", targetMuscle: "Forearm Flexors", equipment: "Barbell", video: yt("wrist curl barbell") },
  { id: "reverse_wrist_curl", name: "Reverse Wrist Curl", muscle: "Arms", targetMuscle: "Forearm Extensors", equipment: "Barbell", video: yt("reverse wrist curl barbell") },

  { id: "hanging_leg_raise", name: "Hanging Leg Raise", muscle: "Core", targetMuscle: "Lower Abs", equipment: "Bodyweight", video: yt("hanging leg raise") },
  { id: "lying_leg_raise", name: "Lying Leg Raise", muscle: "Core", targetMuscle: "Lower Abs", equipment: "Bodyweight", video: yt("lying leg raise") },
  { id: "crunches", name: "Crunches", muscle: "Core", targetMuscle: "Upper Abs", equipment: "Bodyweight", video: yt("crunches") },
  { id: "bicycle_crunches", name: "Bicycle Crunches", muscle: "Core", targetMuscle: "Obliques / Full Core", equipment: "Bodyweight", video: yt("bicycle crunches") },
  { id: "alternate_toe_touch", name: "Alternate Toe Touch", muscle: "Core", targetMuscle: "Upper Abs / Obliques", equipment: "Bodyweight", video: yt("alternate toe touch") },
  { id: "plank", name: "Plank", muscle: "Core", targetMuscle: "Core Stability", equipment: "Bodyweight", video: yt("plank") },
  { id: "cable_crunch", name: "Cable Crunch", muscle: "Core", targetMuscle: "Upper Abs", equipment: "Cable", video: yt("cable crunch") },
  { id: "russian_twist", name: "Russian Twist", muscle: "Core", targetMuscle: "Obliques", equipment: "Bodyweight", video: yt("russian twist") },
  { id: "abs_complex", name: "Abs Complex - Upper/Lower/Oblique", muscle: "Core", targetMuscle: "Full Core", equipment: "Bodyweight", video: yt("abs workout") },

  { id: "incline_walk", name: "Treadmill Incline Walk", muscle: "Cardio", targetMuscle: "Cardio", equipment: "Treadmill", video: yt("treadmill incline walk fat loss") },
  { id: "jump_rope", name: "Jump Rope", muscle: "Cardio", targetMuscle: "Cardio", equipment: "Rope", video: yt("jump rope workout") },
  { id: "cycling", name: "Stationary Cycling", muscle: "Cardio", targetMuscle: "Cardio", equipment: "Bike", video: yt("stationary bike cardio") },
  { id: "underknee_taps", name: "Underknee Taps + Knee Up", muscle: "Cardio", targetMuscle: "Cardio", equipment: "Bodyweight", video: yt("underknee taps knee up") },
  { id: "stretching", name: "Stretching", muscle: "Cardio", targetMuscle: "Mobility", equipment: "Bodyweight", video: yt("full body stretching") },
  { id: "assisted_dips", name: "Assisted Tricep Dips", muscle: "Arms", targetMuscle: "Triceps Overall", equipment: "Machine", video: yt("assisted tricep dips") },
  { id: "jumping_jacks", name: "Jumping Jacks", muscle: "Cardio", targetMuscle: "Full Body Cardio", equipment: "Bodyweight", video: yt("jumping jacks") },
  { id: "bench_dips", name: "Bench Dips", muscle: "Arms", targetMuscle: "Triceps Overall", equipment: "Bodyweight", video: yt("bench dips") },
  { id: "bodyweight_squats", name: "Free Squats", muscle: "Legs", targetMuscle: "Quads / Glutes", equipment: "Bodyweight", video: yt("bodyweight squats") },
  { id: "sliding_walk", name: "Sliding Walk", muscle: "Cardio", targetMuscle: "Cardio", equipment: "Bodyweight", video: yt("sliding walk exercise") },
  { id: "seated_leg_curl", name: "Seated Leg Curl", muscle: "Legs", targetMuscle: "Hamstrings", equipment: "Machine", video: yt("seated leg curl") },
  { id: "warm_up", name: "Warm Up", muscle: "Cardio", targetMuscle: "Mobility", equipment: "Bodyweight", video: yt("warm up routine") },
  { id: "warm_up_legs", name: "Leg Day Warm Up (Lunges & Cycling)", muscle: "Cardio", targetMuscle: "Mobility", equipment: "Bodyweight", video: yt("leg day warm up lunges cycling") },
  { id: "warm_up_stability", name: "Stability Warm Up (Cycling & Dead Hang)", muscle: "Cardio", targetMuscle: "Mobility", equipment: "Bodyweight", video: yt("stability warm up cycling dead hang") },
  { id: "side_plank", name: "Side Plank", muscle: "Core", targetMuscle: "Obliques", equipment: "Bodyweight", video: yt("side plank") },
  { id: "kettlebell_swing", name: "Kettlebell Swing", muscle: "Legs", targetMuscle: "Glutes / Hamstrings", equipment: "Kettlebell", video: yt("kettlebell swing") },
  { id: "kneeling_squat", name: "Kneeling Squat", muscle: "Legs", targetMuscle: "Glutes", equipment: "Bodyweight", video: yt("kneeling squats") },
  { id: "upright_row", name: "Upright Row", muscle: "Shoulders", targetMuscle: "Side Delts / Traps", equipment: "Barbell", video: yt("upright row") },
  { id: "back_extension", name: "Back Extension", muscle: "Back", targetMuscle: "Lower Back", equipment: "Machine", video: yt("back extension") },
];

export const W = Object.fromEntries(WORKOUTS.map((w) => [w.id, w]));
export const DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export const item = (id, sets, reps) => ({ ...W[id], sets, reps });

export const PEOPLE = [
  {
    id: "avirup",
    name: "Avirup",
    goal: "Hybrid Athlete",
    color: "#9B6DFF",
    plan: {
      Mon: { focus: "Triceps & Chest", items: [item("cgbp", 3, "Failure"), item("skull_crusher", 3, "Failure"), item("pec_dec_fly", 3, "Failure"), item("bench_dips", 2, "Failure"), item("lateral_raise", 3, "Failure"), item("arnold_press", 2, "Failure")] },
      Tue: { focus: "Biceps & Back", items: [item("barbell_curl", 3, "Failure"), item("incline_bicep_curl", 3, "Failure"), item("hammer_curl", 2, "Failure"), item("barbell_row", 3, "Failure"), item("shrugs", 3, "Failure"), item("face_pull", 3, "Failure")] },
      Wed: { focus: "Mobility & Abs", items: [item("stretching", 2, "Failure"), item("abs_complex", 10, "Failure")] },
      Thu: { focus: "Triceps, Chest, Shoulders", items: [item("incline_db_press", 3, "Failure"), item("cable_fly", 3, "Failure"), item("skull_crusher", 3, "Failure"), item("tricep_kickback", 2, "Failure"), item("lateral_raise", 3, "Failure"), item("upright_row", 2, "Failure")] },
      Fri: { focus: "Legs", items: [item("squat", 3, "Failure"), item("rdl", 3, "Failure"), item("leg_press", 2, "Failure"), item("seated_leg_curl", 2, "Failure"), item("lying_leg_curl", 2, "Failure"), item("calf_raise", 3, "Failure")] },
      Sat: { focus: "Biceps & Back", items: [item("pullups", 2, "Failure"), item("lat_pulldown", 2, "Failure"), item("chest_supported_db_row", 3, "Failure"), item("one_arm_db_row", 2, "Failure"), item("back_extension", 2, "Failure"), item("preacher_curl", 3, "Failure"), item("rear_delt_fly", 3, "Failure")] },
      Sun: { focus: "Rest", items: [] },
    },
  },
  {
    id: "apurba",
    name: "Apurba",
    goal: "Lean Muscle Building",
    color: "#4A91EB",
    plan: {
      Mon: { focus: "Pull Day", items: [item("pullups", 3, "Failure"), item("lat_pulldown", 4, "8-10"), item("one_arm_db_row", 3, "12"), item("chest_supported_db_row", 3, "10-12"), item("deadlift", 2, "10-12"), item("barbell_curl", 3, "8-10")] },
      Tue: { focus: "Push Day", items: [item("bench_press", 3, "12"), item("upper_cable_fly", 2, "12"), item("cable_fly", 3, "12"), item("dips", 2, "Failure"), item("tricep_pushdown", 3, "12"), item("wrist_curl", 2, "12-16"), item("reverse_wrist_curl", 2, "12-16")] },
      Wed: { focus: "Leg Day", items: [item("hack_squat", 3, "12"), item("rdl", 3, "12"), item("leg_press", 2, "12"), item("lying_leg_curl", 2, "8-10"), item("leg_extension", 2, "8-10"), item("calf_raise", 3, "15")] },
      Thu: { focus: "Rest", items: [] },
      Fri: { focus: "Shoulder & Core", items: [item("incline_db_press", 3, "12"), item("db_shoulder_press", 3, "12"), item("lateral_raise", 4, "12-16"), item("rear_delt_fly", 4, "12-16"), item("shrugs", 3, "12"), item("lying_leg_raise", 2, "15"), item("crunches", 2, "15"), item("bicycle_crunches", 2, "15")] },
      Sat: { focus: "Arm Day", items: [item("incline_bicep_curl", 3, "10-12"), item("preacher_curl", 3, "12"), item("hammer_curl", 3, "10-12"), item("cgbp", 3, "10-12"), item("triceps_ohp", 3, "10-12"), item("tricep_kickback", 3, "10-12")] },
      Sun: { focus: "Rest", items: [] },
    },
  },
  {
    id: "popy",
    name: "Popy",
    goal: "Muscle Building",
    color: "#F5A623",
    plan: {
      Mon: { focus: "Pull Day", items: [item("pullups", 2, "Failure"), item("lat_pulldown", 3, "10-12"), item("seated_row", 3, "10-12"), item("one_arm_db_row", 2, "10-12"), item("biceps_superset", 3, "Failure"), item("abs_complex", 6, "2/2/2")] },
      Tue: { focus: "Heavy Leg Day", items: [item("sumo_squat", 2, "Warmup"), item("hack_squat", 3, "Heavy"), item("rdl", 3, "8-10"), item("leg_extension", 2, "10-12"), item("lying_leg_curl", 2, "10-12"), item("calf_raise", 3, "15"), item("stretching", 1, "5-10 min")] },
      Wed: { focus: "Rest", items: [] },
      Thu: { focus: "Push Day", items: [item("pushups", 2, "Failure"), item("bench_press", 2, "8-10"), item("incline_db_press", 2, "8-10"), item("pec_dec_fly", 2, "12"), item("triceps_ohp", 3, "10-12"), item("abs_complex", 6, "Failure")] },
      Fri: { focus: "Shoulder & Partial Leg", items: [item("dead_hang", 3, "30 sec"), item("lateral_raise", 3, "12-15"), item("rear_delt_fly", 3, "12-15"), item("shrugs", 2, "12"), item("hip_thrust", 3, "10-12"), item("leg_press", 2, "10-12"), item("incline_walk", 1, "10 min")] },
      Sat: { focus: "Arms & Core Stability", items: [item("preacher_curl", 3, "10-12"), item("hammer_curl", 2, "10-12"), item("tricep_pushdown", 3, "10-12"), item("assisted_dips", 2, "10-12"), item("plank", 3, "2m, 1:30, 1m"), item("underknee_taps", 2, "50s reps")] },
      Sun: { focus: "Rest", items: [] },
    },
  },
  {
    id: "kushal",
    name: "Kushal",
    goal: "Body Recomposition",
    color: "#4DD9E8",
    plan: {
      Mon: { focus: "Push Day", items: [item("bench_press", 3, "8-10"), item("pec_dec_fly", 3, "8-10"), item("db_shoulder_press", 2, "10-12"), item("lateral_raise", 3, "10-12"), item("crunches", 2, "10-12"), item("lying_leg_raise", 2, "10-12"), item("jumping_jacks", 2, "10-12"), item("incline_walk", 1, "10 min")] },
      Tue: { focus: "Rest", items: [] },
      Wed: { focus: "Leg Day", items: [item("squat", 3, "8-10"), item("leg_press", 2, "8-10"), item("seated_leg_curl", 3, "10-12"), item("lying_leg_curl", 3, "10-12"), item("calf_raise", 3, "10-12"), item("stretching", 2, "10-12")] },
      Thu: { focus: "Rest", items: [] },
      Fri: { focus: "Pull Day", items: [item("lat_pulldown", 3, "8-10"), item("seated_row", 3, "8-10"), item("one_arm_db_row", 2, "8-10"), item("rear_delt_fly", 3, "10-12"), item("crunches", 2, "10-12"), item("lying_leg_raise", 2, "10-12"), item("jumping_jacks", 2, "10-12"), item("incline_walk", 1, "10 min")] },
      Sat: { focus: "Arms & Mobility", items: [item("preacher_curl", 3, "10-12"), item("alternate_db_curl", 2, "10-12"), item("triceps_ohp", 3, "10-12"), item("bench_dips", 2, "10-12"), item("bodyweight_squats", 3, "8-10"), item("underknee_taps", 2, "10-12"), item("cycling", 1, "10-15 min"), item("sliding_walk", 1, "10 min"), item("incline_walk", 1, "10 min")] },
      Sun: { focus: "Rest", items: [] },
    },
  },
  {
    id: "madhusree",
    name: "Madhusree",
    goal: "Overall Weight Loss",
    color: "#34C87A",
    plan: {
      Mon: { focus: "Push Day", items: [item("bench_press", 3, "8-10"), item("pec_dec_fly", 3, "8-10"), item("db_shoulder_press", 2, "10-12"), item("lateral_raise", 3, "10-12"), item("crunches", 2, "10-12"), item("lying_leg_raise", 2, "10-12"), item("jumping_jacks", 2, "10-12"), item("incline_walk", 1, "10 min")] },
      Tue: { focus: "Leg Day", items: [item("squat", 3, "8-10"), item("leg_press", 2, "8-10"), item("seated_leg_curl", 3, "10-12"), item("lying_leg_curl", 3, "10-12"), item("calf_raise", 3, "10-12"), item("stretching", 2, "10-12")] },
      Wed: { focus: "Rest", items: [] },
      Thu: { focus: "Pull Day", items: [item("lat_pulldown", 3, "8-10"), item("seated_row", 3, "8-10"), item("one_arm_db_row", 2, "8-10"), item("rear_delt_fly", 3, "10-12"), item("crunches", 2, "10-12"), item("lying_leg_raise", 2, "10-12"), item("jumping_jacks", 2, "10-12"), item("incline_walk", 1, "10 min")] },
      Fri: { focus: "Arms & Cardio", items: [item("preacher_curl", 3, "10-12"), item("alternate_db_curl", 2, "10-12"), item("triceps_ohp", 3, "10-12"), item("bench_dips", 2, "10-12"), item("bodyweight_squats", 3, "8-10"), item("underknee_taps", 2, "10-12"), item("cycling", 1, "10-15 min"), item("sliding_walk", 1, "10 min"), item("incline_walk", 1, "10 min")] },
      Sat: { focus: "5th Day Add-on", items: [item("lunges", 3, "8-10"), item("bodyweight_squats", 3, "8-10"), item("sumo_squat", 3, "8-10"), item("plank", 3, "1 min"), item("russian_twist", 3, "10-12"), item("alternate_toe_touch", 3, "10-12"), item("crunches", 3, "10-12")] },
      Sun: { focus: "Rest", items: [] },
    },
  },
  {
    id: "sayani",
    name: "Sayani",
    goal: "Lower Body focused Weight Loss",
    color: "#FF6B9D",
    plan: {
      Mon: { focus: "Pull Day", items: [item("lat_pulldown", 3, "12"), item("seated_row", 3, "12"), item("one_arm_db_row", 2, "12"), item("rear_delt_fly", 3, "12"), item("preacher_curl", 3, "12"), item("plank", 3, "60s"), item("russian_twist", 2, "15"), item("incline_walk", 1, "10 min")] },
      Tue: { focus: "Leg Day", items: [item("warm_up_legs", 1, "Warmup"), item("squat", 3, "12"), item("leg_press", 2, "12"), item("leg_extension", 2, "12"), item("lying_leg_curl", 2, "12"), item("calf_raise", 3, "15"), item("stretching", 2, "12")] },
      Wed: { focus: "Push Day", items: [item("bench_press", 3, "12"), item("pec_dec_fly", 3, "12"), item("db_shoulder_press", 2, "12"), item("lateral_raise", 3, "12"), item("triceps_ohp", 3, "12"), item("crunches", 2, "12"), item("lying_leg_raise", 3, "12"), item("incline_walk", 1, "10 min")] },
      Thu: { focus: "Rest", items: [] },
      Fri: { focus: "Lower Stability", items: [item("warm_up_stability", 1, "Warmup"), item("hip_thrust", 3, "12"), item("sumo_squat", 3, "12"), item("kneeling_squat", 3, "12"), item("side_plank", 2, "45s/side"), item("kettlebell_swing", 3, "15")] },
      Sat: { focus: "Arms & Cardio", items: [item("alternate_db_curl", 3, "12"), item("barbell_curl", 2, "12"), item("bench_dips", 2, "12"), item("tricep_pushdown", 3, "12"), item("incline_walk", 1, "15 min")] },
      Sun: { focus: "Rest", items: [] },
    },
  },
  {
    id: "sanjukta",
    name: "Sanjukta",
    goal: "Upper Body focused Weight Loss",
    color: "#FF7A59",
    plan: {
      Mon: { focus: "Pull Day", items: [item("lat_pulldown", 3, "12"), item("seated_row", 3, "12"), item("one_arm_db_row", 2, "12"), item("rear_delt_fly", 3, "12"), item("preacher_curl", 3, "12"), item("plank", 3, "60s"), item("russian_twist", 2, "15"), item("incline_walk", 1, "10 min")] },
      Tue: { focus: "Leg Day", items: [item("warm_up_legs", 1, "Warmup"), item("squat", 3, "12"), item("leg_press", 2, "12"), item("leg_extension", 2, "12"), item("lying_leg_curl", 2, "12"), item("calf_raise", 3, "15"), item("stretching", 2, "12")] },
      Wed: { focus: "Push Day", items: [item("bench_press", 3, "12"), item("pec_dec_fly", 3, "12"), item("db_shoulder_press", 2, "12"), item("lateral_raise", 3, "12"), item("triceps_ohp", 3, "12"), item("crunches", 2, "12"), item("lying_leg_raise", 3, "12"), item("incline_walk", 1, "10 min")] },
      Thu: { focus: "Rest", items: [] },
      Fri: { focus: "Lower Stability", items: [item("warm_up_stability", 1, "Warmup"), item("hip_thrust", 3, "12"), item("sumo_squat", 3, "12"), item("kneeling_squat", 3, "12"), item("side_plank", 2, "45s/side"), item("kettlebell_swing", 3, "15")] },
      Sat: { focus: "Arms & Cardio", items: [item("alternate_db_curl", 3, "12"), item("barbell_curl", 2, "12"), item("bench_dips", 2, "12"), item("tricep_pushdown", 3, "12"), item("incline_walk", 1, "15 min")] },
      Sun: { focus: "Rest", items: [] },
    },
  }
];
