export const MUSCLES = {
  Chest: "#4A91EB",
  Back: "#9B6DFF",
  Legs: "#34C87A",
  Shoulders: "#F5A623",
  Arms: "#FF6B9D",
  Core: "#4DD9E8",
  Cardio: "#FF7A59",
};

const yt = (q) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q + " proper form")}`;

export const WORKOUTS = [
  { id: "bench_press", name: "Smith Machine Bench Press", muscle: "Chest", targetMuscle: "Mid Chest", equipment: "Smith Machine", video: yt("smith machine bench press") },
  { id: "incline_db_press", name: "Incline Dumbbell Press", muscle: "Chest", targetMuscle: "Upper Chest", equipment: "Dumbbell", video: yt("incline dumbbell press") },
  { id: "pushups", name: "Push-ups", muscle: "Chest", targetMuscle: "Overall Chest", equipment: "Bodyweight", video: yt("pushups") },
  { id: "cable_fly", name: "Lower Chest Fly", muscle: "Chest", targetMuscle: "Lower Chest", equipment: "Cable / Machine", video: yt("lower chest fly") },
  { id: "upper_cable_fly", name: "Upper Chest Cable Fly", muscle: "Chest", targetMuscle: "Upper Chest", equipment: "Cable", video: yt("upper chest cable fly") },
  { id: "dips", name: "Chest Dips", muscle: "Chest", targetMuscle: "Lower Chest", equipment: "Dip bars", video: yt("chest dips") },
  { id: "pec_dec_fly", name: "Pec Dec Fly", muscle: "Chest", targetMuscle: "Inner Chest", equipment: "Machine", video: yt("pec dec fly") },

  { id: "pullups", name: "Pull-ups", muscle: "Back", targetMuscle: "Upper Lats", equipment: "Bodyweight", video: yt("pull ups") },
  { id: "barbell_row", name: "Bent Over Barbell Row", muscle: "Back", targetMuscle: "Overall Back", equipment: "Barbell", video: yt("bent over barbell row") },
  { id: "lat_pulldown", name: "Lat Pulldown", muscle: "Back", targetMuscle: "Upper Lats", equipment: "Cable", video: yt("lat pulldown") },
  { id: "seated_row", name: "Seated Cable Row", muscle: "Back", targetMuscle: "Mid Back", equipment: "Cable", video: yt("seated cable row") },
  { id: "deadlift", name: "Deadlift", muscle: "Back", targetMuscle: "Lower Back", equipment: "Barbell", video: yt("deadlift") },
  { id: "one_arm_db_row", name: "One Arm Dumbbell Row", muscle: "Back", targetMuscle: "Lower Lats", equipment: "Dumbbell", video: yt("one arm dumbbell row") },
  { id: "chest_supported_db_row", name: "Chest Supported Dumbbell Row", muscle: "Back", targetMuscle: "Mid Back", equipment: "Dumbbell", video: yt("chest supported dumbbell row") },
  { id: "single_arm_high_row", name: "Single Arm High Cable Row", muscle: "Back", targetMuscle: "Upper Lats", equipment: "Cable", video: yt("single arm high cable row") },
  { id: "dead_hang", name: "Dead Hang", muscle: "Back", targetMuscle: "Grip / Lats", equipment: "Bodyweight", video: yt("dead hang") },

  { id: "squat", name: "Barbell Squat", muscle: "Legs", targetMuscle: "Quads / Glutes", equipment: "Barbell", video: yt("barbell squat") },
  { id: "rdl", name: "Romanian Deadlift", muscle: "Legs", targetMuscle: "Hamstrings", equipment: "Dumbbell", video: yt("romanian deadlift dumbbell") },
  { id: "leg_press", name: "Leg Press", muscle: "Legs", targetMuscle: "Quads", equipment: "Machine", video: yt("leg press") },
  { id: "lunges", name: "Walking Lunges", muscle: "Legs", targetMuscle: "Quads / Glutes", equipment: "Dumbbell", video: yt("walking lunges") },
  { id: "calf_raise", name: "Standing Calf Raise", muscle: "Legs", targetMuscle: "Calves", equipment: "Machine", video: yt("standing calf raise") },
  { id: "sumo_squat", name: "Heavy Sumo Squat", muscle: "Legs", targetMuscle: "Abductor / Inner Thighs", equipment: "Dumbbell", video: yt("heavy sumo squat dumbbell") },
  { id: "hack_squat", name: "Hack Squat", muscle: "Legs", targetMuscle: "Overall Quad", equipment: "Machine", video: yt("hack squat") },
  { id: "lying_leg_curl", name: "Lying Hamstring Curl", muscle: "Legs", targetMuscle: "Hamstrings", equipment: "Machine", video: yt("lying hamstring curl") },
  { id: "leg_extension", name: "Leg Extension", muscle: "Legs", targetMuscle: "Inner Quad", equipment: "Machine", video: yt("leg extension") },
  { id: "hip_thrust", name: "Hip Thrust", muscle: "Legs", targetMuscle: "Glutes", equipment: "Barbell", video: yt("hip thrust") },

  { id: "ohp", name: "Overhead Press", muscle: "Shoulders", targetMuscle: "Front Delts", equipment: "Barbell", video: yt("overhead press") },
  { id: "lateral_raise", name: "Lateral Raise", muscle: "Shoulders", targetMuscle: "Side Delts", equipment: "Dumbbell", video: yt("lateral raise") },
  { id: "front_raise", name: "Front Raise", muscle: "Shoulders", targetMuscle: "Front Delts", equipment: "Dumbbell", video: yt("front raise") },
  { id: "face_pull", name: "Face Pull", muscle: "Shoulders", targetMuscle: "Rear Delts", equipment: "Cable", video: yt("face pull") },
  { id: "arnold_press", name: "Arnold Press", muscle: "Shoulders", targetMuscle: "Front / Side Delts", equipment: "Dumbbell", video: yt("arnold press") },
  { id: "rear_delt_fly", name: "Rear Delt Fly", muscle: "Shoulders", targetMuscle: "Rear Delts", equipment: "Machine", video: yt("rear delt fly") },
  { id: "shrugs", name: "Shrugs", muscle: "Shoulders", targetMuscle: "Traps", equipment: "Dumbbell", video: yt("shrugs") },

  { id: "incline_bicep_curl", name: "Incline Bicep Curl", muscle: "Arms", targetMuscle: "Biceps Long Head", equipment: "Dumbbell", video: yt("incline bicep curl") },
  { id: "alternate_db_curl", name: "Alternate Dumbbell Curl", muscle: "Arms", targetMuscle: "Biceps", equipment: "Dumbbell", video: yt("alternate dumbbell curl") },
  { id: "barbell_curl", name: "Barbell Curl", muscle: "Arms", targetMuscle: "Biceps", equipment: "Barbell", video: yt("barbell curl") },
  { id: "hammer_curl", name: "Hammer Curl", muscle: "Arms", targetMuscle: "Brachialis", equipment: "Dumbbell", video: yt("hammer curl") },
  { id: "preacher_curl", name: "Preacher Curl", muscle: "Arms", targetMuscle: "Biceps Short Head", equipment: "Machine", video: yt("preacher curl") },
  { id: "cable_bicep_curl", name: "Cable Bicep Curl", muscle: "Arms", targetMuscle: "Biceps", equipment: "Cable", video: yt("cable bicep curl") },
  { id: "biceps_superset", name: "Biceps Superset", muscle: "Arms", targetMuscle: "Biceps", equipment: "Varies", video: yt("biceps superset") },

  { id: "triceps_ohp", name: "Overhead Tricep Extension", muscle: "Arms", targetMuscle: "Triceps Long Head", equipment: "Dumbbell", video: yt("overhead tricep extension") },
  { id: "tricep_pushdown", name: "Tricep Pushdown", muscle: "Arms", targetMuscle: "Triceps Lateral Head", equipment: "Cable", video: yt("tricep pushdown") },
  { id: "cgbp", name: "Close-Grip Bench Press", muscle: "Arms", targetMuscle: "Triceps Overall", equipment: "Barbell", video: yt("close grip bench press") },
  { id: "skull_crusher", name: "Skull Crusher", muscle: "Arms", targetMuscle: "Triceps Long Head", equipment: "Barbell", video: yt("skull crusher") },
  { id: "tricep_kickback", name: "Tricep Kickback", muscle: "Arms", targetMuscle: "Triceps Lateral Head", equipment: "Cable", video: yt("cable tricep kickback") },
  { id: "wrist_curl", name: "Wrist Curl", muscle: "Arms", targetMuscle: "Forearm Flexors", equipment: "Barbell", video: yt("wrist curl barbell") },
  { id: "reverse_wrist_curl", name: "Reverse Wrist Curl", muscle: "Arms", targetMuscle: "Forearm Extensors", equipment: "Barbell", video: yt("reverse wrist curl barbell") },

  { id: "hanging_leg_raise", name: "Hanging Leg Raise", muscle: "Core", targetMuscle: "Lower Abs", equipment: "Bodyweight", video: yt("hanging leg raise") },
  { id: "plank", name: "Plank", muscle: "Core", targetMuscle: "Core Stability", equipment: "Bodyweight", video: yt("plank") },
  { id: "cable_crunch", name: "Cable Crunch", muscle: "Core", targetMuscle: "Upper Abs", equipment: "Cable", video: yt("cable crunch") },
  { id: "russian_twist", name: "Russian Twist", muscle: "Core", targetMuscle: "Obliques", equipment: "Bodyweight", video: yt("russian twist") },
  { id: "abs_complex", name: "Abs Complex", muscle: "Core", targetMuscle: "Full Core", equipment: "Bodyweight", video: yt("abs workout") },

  { id: "incline_walk", name: "Treadmill Incline Walk", muscle: "Cardio", targetMuscle: "Cardio", equipment: "Treadmill", video: yt("treadmill incline walk fat loss") },
  { id: "jump_rope", name: "Jump Rope", muscle: "Cardio", targetMuscle: "Cardio", equipment: "Rope", video: yt("jump rope workout") },
  { id: "cycling", name: "Stationary Cycling", muscle: "Cardio", targetMuscle: "Cardio", equipment: "Bike", video: yt("stationary bike cardio") },
  { id: "underknee_taps", name: "Underknee Taps + Knee Up", muscle: "Cardio", targetMuscle: "Cardio", equipment: "Bodyweight", video: yt("underknee taps knee up") },
];

export const W = Object.fromEntries(WORKOUTS.map((w) => [w.id, w]));
export const DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export const item = (id, sets, reps) => ({ ...W[id], sets, reps });

export const PEOPLE = [
  {
    id: "avirup",
    name: "Avirup",
    goal: "Hybrid Athlete",
    color: "#9B6DFF",
    plan: {
      Mon: { focus: "Upper Heavy", items: [item("bench_press", 5, "3-5"), item("barbell_row", 5, "3-5"), item("ohp", 4, "5")] },
      Tue: { focus: "Lower Heavy", items: [item("squat", 5, "3-5"), item("rdl", 4, "5"), item("calf_raise", 3, "10")] },
      Wed: { focus: "Rest", items: [] },
      Thu: { focus: "Upper Volume", items: [item("incline_db_press", 4, "6-8"), item("pullups", 4, "6-8"), item("cgbp", 3, "6-8")] },
      Fri: { focus: "Lower Volume", items: [item("deadlift", 4, "4-6"), item("leg_press", 4, "8"), item("lying_leg_curl", 3, "8-10")] },
      Sat: { focus: "Accessory", items: [item("face_pull", 3, "15"), item("barbell_curl", 3, "8"), item("plank", 3, "60s")] },
      Sun: { focus: "Rest", items: [] },
    },
  },
  {
    id: "apurba",
    name: "Apurba",
    goal: "V Taper Aestetic",
    color: "#4A91EB",
    plan: {
      Mon: { focus: "Push", items: [item("bench_press", 4, "6-8"), item("incline_db_press", 3, "8-10"), item("ohp", 3, "8-10"), item("lateral_raise", 4, "12-15"), item("tricep_pushdown", 3, "10-12")] },
      Tue: { focus: "Pull", items: [item("pullups", 4, "6-10"), item("barbell_row", 4, "8-10"), item("lat_pulldown", 3, "10-12"), item("face_pull", 3, "15"), item("barbell_curl", 3, "10-12")] },
      Wed: { focus: "Legs", items: [item("squat", 4, "6-8"), item("rdl", 3, "8-10"), item("leg_press", 3, "10-12"), item("calf_raise", 4, "15")] },
      Thu: { focus: "Push", items: [item("dips", 3, "8-10"), item("cable_fly", 3, "12-15"), item("arnold_press", 3, "8-10"), item("lateral_raise", 4, "15")] },
      Fri: { focus: "Pull", items: [item("deadlift", 3, "5"), item("seated_row", 3, "10-12"), item("hammer_curl", 3, "10-12"), item("plank", 3, "45s")] },
      Sat: { focus: "Legs + Core", items: [item("lunges", 3, "12/leg"), item("lying_leg_curl", 3, "12"), item("hanging_leg_raise", 3, "12"), item("cable_crunch", 3, "15")] },
      Sun: { focus: "Rest", items: [] },
    },
  },
  {
    id: "popy",
    name: "Popy",
    goal: "Muscle Building",
    color: "#F5A623",
    plan: {
      Mon: { focus: "Upper Heavy", items: [item("pullups", 2, "Failure"), item("lat_pulldown", 3, "10-12"), item("seated_row", 3, "10-12"), item("one_arm_db_row", 2, "10-12"), item("biceps_superset", 3, "Failure"), item("abs_complex", 6, "2/2/2")] },
      Tue: { focus: "Leg Day", items: [item("sumo_squat", 2, "Warmup"), item("hack_squat", 3, "Heavy"), item("rdl", 3, "8-10"), item("leg_extension", 2, "10-12"), item("lying_leg_curl", 2, "10-12"), item("calf_raise", 3, "15")] },
      Wed: { focus: "Rest", items: [] },
      Thu: { focus: "Push Day", items: [item("pushups", 2, "Failure"), item("bench_press", 2, "8-10"), item("incline_db_press", 2, "8-10"), item("pec_dec_fly", 2, "12"), item("triceps_ohp", 3, "10-12"), item("abs_complex", 6, "Failure")] },
      Fri: { focus: "Shoulder, Partially Leg", items: [item("dead_hang", 3, "30 sec"), item("hip_thrust", 3, "10-12"), item("leg_press", 2, "10-12"), item("lateral_raise", 3, "12-15"), item("rear_delt_fly", 3, "12-15"), item("shrugs", 2, "12"), item("incline_walk", 1, "10 min")] },
      Sat: { focus: "Arms, Stability, Cardio", items: [item("preacher_curl", 3, "10-12"), item("hammer_curl", 2, "10-12"), item("tricep_pushdown", 3, "10-12"), item("dips", 2, "10-12"), item("plank", 3, "2m, 1:30, 1m"), item("underknee_taps", 2, "50s reps")] },
      Sun: { focus: "Rest", items: [] },
    },
  },
  {
    id: "kushal",
    name: "Kushal",
    goal: "Fat burning & Recomposition",
    color: "#4DD9E8",
    plan: {
      Mon: { focus: "Power + Push", items: [item("bench_press", 4, "5"), item("ohp", 3, "6"), item("dips", 3, "10")] },
      Tue: { focus: "Speed + Legs", items: [item("squat", 4, "5"), item("lunges", 3, "10/leg"), item("jump_rope", 1, "6 min")] },
      Wed: { focus: "Pull + Core", items: [item("pullups", 4, "8"), item("barbell_row", 3, "8"), item("hanging_leg_raise", 3, "12")] },
      Thu: { focus: "Conditioning", items: [item("cycling", 1, "20 min"), item("jump_rope", 1, "8 min"), item("plank", 3, "50s")] },
      Fri: { focus: "Full Body Strength", items: [item("deadlift", 4, "5"), item("incline_db_press", 3, "8"), item("face_pull", 3, "15")] },
      Sat: { focus: "Mobility + Core", items: [item("russian_twist", 3, "20"), item("cable_crunch", 3, "15")] },
      Sun: { focus: "Rest", items: [] },
    },
  },
  {
    id: "madhusree",
    name: "Madhusree",
    goal: "Weight Loss",
    color: "#34C87A",
    plan: {
      Mon: { focus: "Full Body Circuit", items: [item("squat", 3, "15"), item("pushups", 3, "12-15"), item("seated_row", 3, "15"), item("jump_rope", 1, "5 min")] },
      Tue: { focus: "Cardio", items: [item("incline_walk", 1, "30 min"), item("plank", 3, "40s")] },
      Wed: { focus: "Full Body Circuit", items: [item("lunges", 3, "12/leg"), item("lat_pulldown", 3, "15"), item("lateral_raise", 3, "15"), item("cable_crunch", 3, "15")] },
      Thu: { focus: "Rest", items: [] },
      Fri: { focus: "Full Body Circuit", items: [item("leg_press", 3, "15"), item("cable_fly", 3, "15"), item("hammer_curl", 3, "12"), item("russian_twist", 3, "20")] },
      Sat: { focus: "Cardio", items: [item("cycling", 1, "30 min"), item("hanging_leg_raise", 3, "10")] },
      Sun: { focus: "Rest", items: [] },
    },
  },
  {
    id: "sayani",
    name: "Sayani",
    goal: "Weight Loss & Lower Fat burning",
    color: "#FF6B9D",
    plan: {
      Mon: { focus: "Full Body", items: [item("squat", 3, "10-12"), item("bench_press", 3, "10"), item("seated_row", 3, "12"), item("plank", 3, "45s")] },
      Tue: { focus: "Cardio + Mobility", items: [item("incline_walk", 1, "25 min")] },
      Wed: { focus: "Full Body", items: [item("lunges", 3, "10/leg"), item("lat_pulldown", 3, "12"), item("ohp", 3, "10"), item("russian_twist", 3, "15")] },
      Thu: { focus: "Rest", items: [] },
      Fri: { focus: "Full Body", items: [item("rdl", 3, "10"), item("pushups", 3, "10-12"), item("hammer_curl", 3, "12"), item("cable_crunch", 3, "12")] },
      Sat: { focus: "Cardio", items: [item("cycling", 1, "25 min"), item("jump_rope", 1, "3 min")] },
      Sun: { focus: "Rest", items: [] },
    },
  },
  {
    id: "sanjukta",
    name: "Sanjukta",
    goal: "weight Loss & Upper Fat burning",
    color: "#FF7A59",
    plan: {
      Mon: { focus: "Full Body Circuit", items: [item("squat", 3, "15"), item("pushups", 3, "12-15"), item("seated_row", 3, "15"), item("jump_rope", 1, "5 min")] },
      Tue: { focus: "Cardio", items: [item("incline_walk", 1, "30 min"), item("plank", 3, "40s")] },
      Wed: { focus: "Full Body Circuit", items: [item("lunges", 3, "12/leg"), item("lat_pulldown", 3, "15"), item("lateral_raise", 3, "15"), item("cable_crunch", 3, "15")] },
      Thu: { focus: "Rest", items: [] },
      Fri: { focus: "Full Body Circuit", items: [item("leg_press", 3, "15"), item("cable_fly", 3, "15"), item("hammer_curl", 3, "12"), item("russian_twist", 3, "20")] },
      Sat: { focus: "Cardio", items: [item("cycling", 1, "30 min"), item("hanging_leg_raise", 3, "10")] },
      Sun: { focus: "Rest", items: [] },
    },
  }
];
